services:
  - type: web
    name: streamlit-app
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "streamlit run src/app.py"
    preDeployCommand: "apt-get install portaudio19-dev python-all-dev"
